name: UHC
version: 0.1
author: chasertw123

description: Ultra Hardcore minigame!
main: me.chasertw123.uhc.Main
depends: [Multiverse-Core]

commands:
  admin:
    description: Admin command
    permission: uhc.admin
  team:
    description: Team command
  chat:
    description: Chat command
  leave:
    description: Leave command
permissions:
  uhc.sign.create:
    description: Create UHC signs.
    default: op
  uhc.chat:
    description: Be able to set your chat type.
    default: true
  uhc.admin:
    description: Access to admin command and chat
    default: op