name: UHC
version: 0.1
author: chasertw123

description: Ultra Hardcore minigame!
main: me.chasertw123.uhc.Main
depends: [Multiverse-Core]

commands:
  admin:
    description: Admin command
  team:
    description: Team command
  chat:
    description: Chat command
  leave:
    description: Leave command
permissions:
  uhc.sign.create:
    description: Create UHC signs.
    default: op